# Generated by Django 4.2 on 2023-05-05 18:08

from django.db import migrations, models

import src.general.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[src.general.validators.HexStringValidator(64)]
            ),
        ),
    ]
